# Generated by Django 3.2.8 on 2021-11-10 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_employeeleave'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectFiles',
            new_name='ProjectFile',
        ),
    ]
