# Generated by Django 3.2.8 on 2021-11-10 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20211110_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('handler', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_handler', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
